name: Auto Deploy on Release Commit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    if: startsWith(github.event.head_commit.message, 'release:')

    steps:
      - uses: actions/checkout@v3

      - name: Stop old containers
        run: |
          try {
            docker compose down
          } catch {
            Write-Host "No containers to stop"
          }

      - name: Build and start containers
        run: docker compose up -d --build
