name: Auto Deploy

on:
  push:
    branches:
      - master  # changed from 'main' to 'master'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop old containers
        run: |
          try {
            docker compose down
          } catch {
            Write-Host "No containers to stop"
          }

      - name: Build and start containers
        run: docker compose up -d --build
